version: '3'
services:
  core:
    build:
      context: ./core
      args:
        # Change according to your details
        REPOSITORY_URL: https://github.com/intevation/OpenSlides.git
        BRANCH: dgb
        COMMIT_SHA: a93bcc17691962060e1814744067cd41ee510609
    image: openslides-dgb
    command: bash -c "rm -rf /app/personal_data/var/static && rm -rf /app/personal_data/var/collected-static && sleep 15 && python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  web:
    build: ./web
    image: os-web
    restart: always
    links:
      - redis
    depends_on:
      - core
      - nginx
    expose:
      - 8000
    environment:
      # Change according to your details
      VIRTUAL_HOST: 'openslides-dgb3.intevation.de'
      LETSENCRYPT_HOST: 'openslides-dgb3.intevation.de'
      LETSENCRYPT_EMAIL: 'admin@intevation.de'
      LETSENCRYPT_TEST: 'true'
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "redisdata:/data"
    networks:
      - back
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
      - "staticfiles:/app/static:ro"
      - "./nginx/default_location:/etc/nginx/vhost.d/default_location"
      - "./nginx/htpasswd:/etc/nginx/.htpasswd"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - front
      - back
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - back
  postgres:
    image: sameersbn/postgresql:9.6-2
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
    environment:
      - DB_USER=openslides
      - DB_PASS=openslides
      - DB_NAME=openslides
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    ports:
      - "5432:5432"
    networks:
      - front
      - back
  pg-slave:
    image: sameersbn/postgresql:9.6-2
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
    environment:
      - REPLICATION_MODE=slave
      - REPLICATION_SSLMODE=on
      - REPLICATION_HOST=openslides-dgb3.intevation.de
      - REPLICATION_PORT=5432
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    networks:
      - back
  filesync:
    build: ./filesync
    image: os-filesync
    restart: always
    volumes:
      - "staticfiles:/app/static"
    environment:
      - REMOTE_MODE=MASTER
      - REMOTE_HOST=openslides-dgb3.intevation.de
      - REMOTE_USER=openslides
      - REMOTE_PASS=openslides
    networks:
      - back
  postfix:
    image: catatnight/postfix
    restart: always
    environment:
      - maildomain=openslides-dgb3.intevation.de
      - smtp_user=openslides:openslides
    networks:
      - back
volumes:
  redisdata:
  dbdata:
  staticfiles:
  certs:
  nginx_vhost:
  nginx_html:
  nginx_conf:
networks:
  front:
  back:
