version: '3'
services:
  core:
    build:
      context: ./core
      args:
        # Change according to your details
        REPOSITORY_URL: https://github.com/intevation/OpenSlides.git
        BRANCH: amnesty
        COMMIT_SHA: 1be357326f441ec5540a0d598114630a166565a9
    image: openslides-ai-protocol
    command: bash -c "rm -rf /app/personal_data/var/static && rm -rf /app/personal_data/var/collected-static && sleep 15 && python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  web:
    build: ./web
    image: os-web
    restart: always
    links:
      - redis
    depends_on:
      - core
      - nginx
    expose:
      - 8000
    environment:
      # Change according to your details
      VIRTUAL_HOST: 'openslides.amnesty-international.de'
      LETSENCRYPT_HOST: 'openslides.amnesty-international.de'
      LETSENCRYPT_EMAIL: 'admin@intevation.de'
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "redisdata:/data"
    networks:
      - back
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
      - "staticfiles:/app/static:ro"
      - "./nginx/default_location:/etc/nginx/vhost.d/default_location"
      - "./nginx/htpasswd:/etc/nginx/.htpasswd"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - front
      - back
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - back
  postgres:
    image: postgres
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
    networks:
      - back
  postfix:
    image: catatnight/postfix
    restart: always
    environment:
      - maildomain=openslides.amnesty-international.de 
      - smtp_user=openslides:openslides
    networks:
      - back
volumes:
  redisdata:
  dbdata:
  staticfiles:
  certs:
  nginx_vhost:
  nginx_html:
  nginx_conf:
networks:
  front:
  back:
