version: '3'
services:
  core:
    build: ./core
    image: openslides
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
#    volumes:
#      - "./core/personal_data:/app/personal_data"
#    networks:
#      - back
  web:
    build: ./web
    image: os-web
    links:
      - redis
    depends_on:
      - core
      - nginx
    expose:
      - 8000
    environment:
      # Image requirement, the virtual host name it will listen too
      # The virtual host is a group of hosts, containers or anything that responds HTTP
      VIRTUAL_HOST: 'localhost'
#    volumes:
#      - "./core/personal_data:/app/personal_data"
#    networks:
#      - back
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
#    networks:
#       - back
  redis:
    image: redis:alpine
#    networks:
#      - back
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
#    networks:
#      - back
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      # It needs to access Docker's API, so we mount the Unix socket
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    # Listens on port 80, accessed by our host on http://localhost
    ports:
      - "80:80"
    environment:
      - ENABLE_IPV6=true
#    networks:
#      - front
#      - back
#  whoami:
#    image: jwilder/whoami
#    environment:
#      - VIRTUAL_HOST=whoami.local
#    networks:
#      - front
#      - back
#networks:
#  front:
#    driver: default
#  back:
#    driver: default
