version: '3'
services:
  core:
    build: ./core
    image: openslides
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: bash -c "DJANGO_SETTINGS_MODULE=settings PYTHONPATH=personal_data/var/ daphne openslides.asgi:channel_layer -p 8000 -b 0.0.0.0"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
  redis:
    image: redis:alpine
  worker:
    image: openslides
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: bash -c "python manage.py runworker"
  nginx:
    image: nginx
#        volumes:
#      - ./nginx/openslides.template:/etc/nginx/conf.d/openslides.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - DAPHNE_HOST=core
      - DAPHNE_PORT=8000
    depends_on:
      - core
    links:
      - core
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/openslides.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/service.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
