version: '3'
services:
  core:
    build: ./core
    image: openslides
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
  web:
    build: ./web
    image: os-web
    links:
      - redis
    depends_on:
      - core
    ports:
            - 8000-8100:8000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
  redis:
    image: redis:alpine
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
