version: '3'
services:
  core:
    build: ./core
    image: openslides
  web:
    build: ./web
    image: os-web
    links:
      - redis
    depends_on:
      - postgres
      - core
    environment:
      - DAPHNE_PORT=8000
    ports:
      - 8000-8100:8000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
  redis:
    image: redis:alpine
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
#  nginx:
#    image: nginx
#    depends_on:
#      - core
#    volumes:
#      - ./nginx/simple.template:/etc/nginx/conf.d/openslides.template
#    ports:
#      - "80:80"
#      - "8000:8000"
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=80
#      - DAPHNE_HOST=core
#      - DAPHNE_PORT=8000
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/openslides.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
